apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5hkLwh4JB464v1FjmuEAcaDuZvx5Yl6yU4b+AyM5UFZkGKOY,iv:OWoYPvv19XAvt8s4YJDQjcvaC/vaBl50d6ax5zNu0zg=,tag:foFtJ6G/pVR35hryh3Gkkg==,type:str]
    credentials.json: ENC[AES256_GCM,data:nT+nLu0f6qoeqddLyU7+4WxkFojbQ/Ndp7Iu1uaA5KKXW2PYEQB+UF+3j4EDneejSoeFxgEhSjhSx5rdLovz4hyCkp4JeDwvXDMbItIXJALAGFxNi8A6inuXU6mPwORkFxI1MdBiyPTsxC1WssWS6D7wi6N/wXufuQFVXFXTbiywmQlKnUqNE9CRF8AH1tSvV74sCiipt2GjG01YbMpJatt7XWXJP9OmIRzkOIyAzA==,iv:xPj5AT3LNAJGKpn5XYFeY83JbJ3+BAGNKN+jvD04oq4=,tag:JU/cQO7z5kOyX3+xyGvGqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRlFITUcyRml1MjRjaWUx
            czNlNCtXcXRFYk9JaGx1Q1R0eEZkaE4yRmpvClZwNHZtcG1panNOZjdid3ZVRVR4
            Z3BOMnhhOW1wekQyVDJ2alhOMkVXZDQKLS0tIE1NYmZDdFp5d3VmUWxEbFNabEgv
            cUJxaEdLYmNZRmlScHNOZnd3MkNoZDQKKe4aEvJ533VpxcxiPhv/3rZPesbJepEU
            9wXR7YcYEITZDlrwixxRpwD8lGa4PdeFhtDohsj8JfwM/xw34huEhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T14:46:21Z"
    mac: ENC[AES256_GCM,data:CgK9Zc2Yntx1qn+9L8khHAB4eD60z2iUH2jbujOONTQlFoHwTfNzFxMDG9BdsmHF7EegwiMoxeqn/Ej4BNWxVKyG/LZ+ZW/YKcrxaRv7c6XRbpF/9EVxmGmRZKhpn3HSQv+C1J6jyMOuhOE3Gb21ViATRAHB9VSe/ebne+179rc=,iv:NZm/yzi6Sw30zqiaNaTw/sOczVvlraYnDX9N3rFuaW0=,tag:BGRpJ8++09hRUzS98WqlNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
