apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:+AfSpN0ZkyBALRM+I90me6fdLzk5oxf+PI7OC37Y9vKRdhg+,iv:N5jWad+CQd38cRSML4RgxyPgdeapu9jWPQ6HKJ6DRpM=,tag:fn8KUg8PqXiTuGVkhupQ8g==,type:str]
    credentials.json: ENC[AES256_GCM,data:2VzZwWJ8eCMBYBjeCOaprHocfI7SirHL3RXWjIFCmm1UNZDRDConL9qpzxipYCnekQlwXsw/xCB5izJ/k2suCOPqfjLREaHPGlnl2OiUpxE9g06TAJsUdQXiq2bQ+FwyeP81yuKSN1I+D1Q9D8z3Teqb2S3bGT7gWTtEBTCNA89CEBJ6gx6eU2/FjeYKZ/ipjVKOcEpkmsbO7aY4oi/FXzvzsGcNRxuR2OceOHDrrw==,iv:DF1OlRVAy8bODSktA/DSfvdco7eyT2xnCaMr+YG2+oc=,tag:goTTFq0qBe6ZSDdp0EDWBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdDFTSEZ2RFJ0Rk5TRVlF
            dWs4bTlkZmFmaXJkRmZNa2VkWkxxQ1VGSEEwClowWHkraXI4YU9jS0g5U1JFWWtr
            Vi94SElJeWRhd1pLMzBXWFJkY2FQUVUKLS0tIG14dCs3bTB5WnZnYklrSm9mam5M
            Myt3ODEvMjlXTDJqMHM4aU1wbGVGb3cKcfc8vDSvrZQIZFnHR8lr0rF+ZU+eGneL
            x+CPLGB0PUk4Wqc8N/Tg/0cEvCElln4DA7vesXmZtwSgj6q/iZmFfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T19:43:38Z"
    mac: ENC[AES256_GCM,data:dQl0ru8Nr9BtJFKtrPOI2hOViC1dDA1cNkxTEOWMvvrMk6xvc1ErP4Ouj45V/DQ8x4dwNn+m4SYDsgERDbp+1c8JWby9aPid7uGmh9sEyWdGHC9EuDvd4wc6EAEqkJsh2YtM6Wk1pmdWG91//i0A2hhGQNkxWFPOq6ULia07w54=,iv:DKwGUC/lK+JDubt0tgm+3moT0e4BOhVPr0aIkl4NVS4=,tag:27DaC7iY4gFGCYoh2oULDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
