apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DLVPjDsY3q1gxu5/NLULbBoqqYSy/nvNChLCduV5p1OBD8xTO0iuoQ==,iv:07NnOTgzam+wT0LtS1VJpBIdRkOPuSCByIPnjfZYTlc=,tag:uSaKF+9w4e+zg4DEpc/g3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRHRWc2pYSEljUjZYUk4z
            KzFkdldjcHdMSko3Nnh1ZEE2emtlVnVtOUVvClhPSTVUZ2ZEMUlQUW9GYnZteVI4
            a0krSVhLU3RzSFl0eFNYQWNNNkxLRHMKLS0tIDlERmFTckxkZW93Q1dWTnNoVmdj
            S3VWWEMxY25OT3JnSWlQaUcySm9pWnMKs3jhuXnv9+FkqqwPitDUnqjn7or/NKq9
            k+tbxN9s5X1L2yabw9KET8JqzEeMSTsy08be6jHU572SgG1RsUch7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T14:46:20Z"
    mac: ENC[AES256_GCM,data:qKjTtAy3LQj/F+VayAGmLL16E/RBIBoBsqUs5abke4wfL/DeJV/oqHFUJPEn27lgAtyuiF0Bzjji0qnMytR2J/MT66OONFaC6qn7YqwHGLRF62BJA5JCePsK/WGprXFZFuRm33NEYFFPMAj8/ye+lC7XYG199nSFVZbzOyjIh7E=,iv:8fYwQ0MRJMmbFq/oLAFVOn7+pwnDz0pJQlp9c61QJVU=,tag:OfM4O5DunA0XBMcXCNiNAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
