apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:qH74F/IulXro8FtuPqUZHXFmjRLwntrzOB5Bai7759AkciBPzfDwfA==,iv:wtoqKe8kK+6L6skQoBP9bXMvLt3XOeIX+W1yrACFofc=,tag:LBQe7CuLGTjbq5ERQ3XPig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbUR0K2dmQjRwUDA3dHZ1
            VlZOUWZaUVhhVytyTlBTYkE2aUtkUnBaZEVNCnlaYTZsTjB3TWRiZVdkSDBIK2lz
            SnhoTGNrc1haRUdkS3NBREh0eDF1SUkKLS0tIDU1YVVCNHhTSjViR0h4Vm11K2dy
            SFZvUThkczJ5WmIxMDY4Ymo4eW11dVEKVuN3HW5/c6xYXTi9qbHq+591VTZGVLSk
            FJoN/dTgdY1aOmk9BR3napPIh/+rkpLw2dAfE3r7GCiNAbkhlyiPyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T16:36:38Z"
    mac: ENC[AES256_GCM,data:nsDlDNLeVOLgwmwiRsH74YRGGbJgsgiuwVI0tFOY4wInhpf7gQl6agi2wcIiAee3Lhp5zKz3iCUHaFWE3NbA077aa3uR7HIg7lisS9EkPbNPWflNt7MZAoBSBHBigmLpBBMgpB6phXWYbvhzgRB1twAV7Bzk6iSwjLIyAb8EEfo=,iv:o3h7EEWUXLrRHV8BV8BENEcyJEKWS/ZXSyBYYRqYqq8=,tag:gH/WonMK8PdLSdwODBJXDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
