---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
components:
  - ../../clusters/chastDev
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./games-mariadb-cluster.yaml
  - ./pterodactyl.yaml
  - ./ut2k4.yaml
