---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lldap
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/security/lldap/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: external-secrets-stores
