# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.100.150.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.100.150.200"
  - "k8s.chast.dev"
  - "cntrlr01.lan.chast.io"
  - "cntrlr02.lan.chast.io"
  - "cntrlr03.lan.chast.io"
  - "wrkr01.lan.chast.io"
  - "wrkr02.lan.chast.io"
  - "wrkr03.lan.chast.io"
  - "wrkr04.lan.chast.io"
additionalMachineCertSans: *sans
clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "cntrlr01"
    ipAddress: "10.100.150.254"
    installDisk: "/dev/nvme0n1"
    talosImageURL: &amdtalos "factory.talos.dev/metal-installer/c94ff372b68451179d010d5e5cf7afa5e229cc6fc0119e87286086b430fa0569"
    controlPlane: true
    # schematic: &amdschematic
    #   customization:
    #     extraKernelArgs:
    #       - -init_on_alloc
    #       - -init_on_free
    #       - -selinux
    #       - apparmor=0
    #       - init_on_alloc=0
    #       - init_on_free=0
    #       - amd_iommu=on
    #       - iommu=pt
    #       - mitigations=off
    #       - security=none
    #       - sysctl.kernel.kexec_load_disabled=1
    #       - talos.auditd.disabled=1
    #       - net.ifnames=0
    #     systemExtensions:
    #       officialExtensions:
    #         - siderolabs/amd-ucode
    #         - siderolabs/amdgpu
    #         - siderolabs/binfmt-misc
    #         - siderolabs/crun
    #         - siderolabs/ctr
    #         - siderolabs/fuse3
    #         - siderolabs/iscsi-tools
    #         - siderolabs/lldpd
    #         - siderolabs/mdadm
    #         - siderolabs/nut-client
    #         - siderolabs/nvme-cli
    #         - siderolabs/uinput
    #         - siderolabs/util-linux-tools
    volumes: &volumes
      # don't let talos use whole disk
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.dev_path == '/dev/nvme0n1'
          minSize: 64GiB
          maxSize: 64GiB
          grow: false
    userVolumes: &userVolumes
      # remaining space on system disk
      - name: lpp-0
        provisioning:
          diskSelector:
            match: disk.dev_path == '/dev/nvme0n1'
          minSize: 64GiB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c8:ff:bf:00:67:e3"
        dhcp: false
        addresses:
          - "10.100.150.254/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
        vip:
          ip: "10.100.150.200"
    extensionServices: &extensionServices
      - name: lldpd
        configFiles:
          - mountPath: /usr/local/etc/lldpd/lldpd.conf
            content: |
              configure lldpd portidsubtype ifname
              configure system description "Talos Node"
    extraManifests: &extraManifests
      - "@./manifests/watchdogtimerconfig.yaml"

  - hostname: "cntrlr02"
    ipAddress: "10.100.150.253"
    installDisk: "/dev/nvme0n1"
    talosImageURL: *amdtalos
    controlPlane: true
    # schematic: *amdschematic
    volumes: *volumes
    userVolumes: *userVolumes
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c8:ff:bf:00:6b:7d"
        dhcp: false
        addresses:
          - "10.100.150.253/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
        vip:
          ip: "10.100.150.200"
    extensionServices: *extensionServices
    extraManifests: *extraManifests

  - hostname: "cntrlr03"
    ipAddress: "10.100.150.252"
    installDisk: "/dev/nvme0n1"
    talosImageURL: *amdtalos
    controlPlane: true
    # schematic: *amdschematic
    volumes: *volumes
    userVolumes: *userVolumes
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c8:ff:bf:00:68:67"
        dhcp: false
        addresses:
          - "10.100.150.252/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
        vip:
          ip: "10.100.150.200"
    extensionServices: *extensionServices
    extraManifests: *extraManifests

  - hostname: "wrkr01"
    ipAddress: "10.100.150.251"
    installDisk: /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U5NJ0Y750893V
    talosImageURL: *amdtalos
    controlPlane: false
    # schematic: *amdschematic
    volumes:
      # don't let talos use whole disk
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.serial == 'S7U5NJ0Y750893V'
          minSize: 64GiB
          maxSize: 64GiB
          grow: false
    userVolumes:
      # remaining space on system disk
      - name: lpp-0
        provisioning:
          diskSelector:
            match: disk.serial == 'S7U5NJ0Y750893V'
          minSize: 64GiB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "78:55:36:01:7f:74"
        dhcp: false
        addresses:
          - "10.100.150.251/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
    extensionServices: *extensionServices
    extraManifests: *extraManifests

  - hostname: "wrkr02"
    ipAddress: "10.100.150.250"
    installDisk: /dev/disk/by-id/nvme-CT1000P3PSSD8_24494CA7AEBF
    talosImageURL: *amdtalos
    controlPlane: false
    # schematic: *amdschematic
    volumes:
      # don't let talos use whole disk
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.serial == '24494CA7AEBF'
          minSize: 64GiB
          maxSize: 64GiB
          grow: false
    userVolumes:
      # remaining space on system disk
      - name: lpp-0
        provisioning:
          diskSelector:
            match: disk.serial == '24494CA7AEBF'
          minSize: 64GiB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "78:55:36:01:7f:3e"
        dhcp: false
        addresses:
          - "10.100.150.250/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
    extensionServices: *extensionServices
    extraManifests: *extraManifests

  - hostname: "wrkr03"
    ipAddress: "10.100.150.249"
    installDisk: /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U5NJ0Y750869N
    talosImageURL: &inteltalos "factory.talos.dev/metal-installer/47c7bd360fcddd3a567ec0760eae4127f3ef47e7f40da7874fe08ead0deabfc4"
    controlPlane: false
    nodeLabels: &nodeLabels
      intel.feature.node.kubernetes.io/gpu: "true"
    # schematic_id: "ccb6793dd7cbd13c42c3f97f10d222d4728da506dd47b55654bd1da602fa6126"
    # schematic: &intelschematic
      # customization:
      #   extraKernelArgs:
      #     - -init_on_alloc
      #     - -init_on_free
      #     - -selinux
      #     - apparmor=0
      #     - i915.enable_guc=3
      #     - init_on_alloc=0
      #     - init_on_free=0
      #     - intel_iommu=on
      #     - iommu=pt
      #     - mitigations=off
      #     - security=none
      #     - sysctl.kernel.kexec_load_disabled=1
      #     - talos.auditd.disabled=1
      #     - net.ifnames=0
      #   systemExtensions:
      #     officialExtensions:
      #       - siderolabs/binfmt-misc
      #       - siderolabs/crun
      #       - siderolabs/ctr
      #       - siderolabs/fuse3
      #       - siderolabs/i915
      #       - siderolabs/intel-ucode
      #       - siderolabs/iscsi-tools
      #       - siderolabs/lldpd
      #       - siderolabs/mdadm
      #       - siderolabs/nut-client
      #       - siderolabs/nvme-cli
      #       - siderolabs/uinput
      #       - siderolabs/util-linux-tools
    volumes:
      # don't let talos use whole disk
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.serial == 'S7U5NJ0Y750869N'
          minSize: 64GiB
          maxSize: 64GiB
          grow: false
    userVolumes:
      # remaining space on system disk
      - name: lpp-0
        provisioning:
          diskSelector:
            match: disk.serial == 'S7U5NJ0Y750869N'
          minSize: 64GiB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:dd:af:2a"
        dhcp: false
        addresses:
          - "10.100.150.249/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
    extensionServices: *extensionServices
    extraManifests: *extraManifests
    patches: &workerIntelPatches
      - "@./patches/worker-intel/machine-sysfs-intel-boost.yaml"

  - hostname: "wrkr04"
    ipAddress: "10.100.150.248"
    installDisk: /dev/disk/by-id/nvme-CT1000P310SSD8_25034D7FFF2E
    talosImageURL: *inteltalos
    controlPlane: false
    nodeLabels: *nodeLabels
    # schematic: *intelschematic
    volumes:
      # don't let talos use whole disk
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.serial == '25034D7FFF2E'
          minSize: 64GiB
          maxSize: 64GiB
          grow: false
    userVolumes:
      # remaining space on system disk
      - name: lpp-0
        provisioning:
          diskSelector:
            match: disk.serial == '25034D7FFF2E'
          minSize: 64GiB
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:da:e8:77"
        dhcp: false
        addresses:
          - "10.100.150.248/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.150.1"
        mtu: 1500
    extensionServices: *extensionServices
    extraManifests: *extraManifests
    patches: *workerIntelPatches

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine.yaml"

