apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D8O8ZzkE5HUW,iv:i/eVE2Gf0iAS2uR60BRljA3xgvyGhZe1sbtQUHFYybI=,tag:v50s5StQDNpDkkbhCJqhQQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:z+ZpvlXD883476T5VSfmCd4CTw0+cbO+,iv:8qv5vyiP/MWr6vnbz/49FAHCY8Uzrq01a/p1+StK4fA=,tag:ps1aZudMW7wPX+EDFigwNA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0ns5N4WrEl38udvNbhvGnZir/kGXRrKuI2emP+m+sdeA6/Zs,iv:VxJaGj5jQaZQKE8s+YRYfZxXnKGPT4KpF9/AmqU3xzg=,tag:jboe0SnOVIqIUy+6zrtdbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNnhlU2xGRmZOTW1jN1Vi
            N2FURHlOK29NUWZ0Q3FENW1takFCcWdtYjJjCm02T1YwV3VyeDI5WHNFSXRxTysz
            S3dQcXpSVDVjQ2FiMktGMFlVYlltbTAKLS0tIFMwOFlEZXVEQnVvL21ES1RzNzZN
            aXBEQkxUY0NXa3p5UC9rUkt0THloVXMKQ1wIbkuY7CMrLX3L1gazrybfHIIxLD/l
            9e+QG9IYNf4e23fnrJofNHfUuzuACRE1DprQ5vGRxOejUspxf538OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T16:44:00Z"
    mac: ENC[AES256_GCM,data:hB4JJn/+217neqHadUEL89tcRf3MHiPiEyzn6J8fPguP8p3c134mXAJ2FIqUDBdRPH3t+i0SrIIfsZox9HRD9vqyyseDOv47QUJ3eeuR0d8Fd3QLODTSq/aUvq8Gw/6346jhbFjm3Wk21AJx0Q3GcYJ4mtdXGySppcvlTsl+7Mo=,iv:I+6nWQUJNs+302RQI/EbR+JA3mSZidI5XC85kktwzR4=,tag:gHFoAGVpSLM58exuvCp9sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
