---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1/job-batch-v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: &name "${APP}-db-init"
  labels:
    app.kubernetes.io/instance: *name
    app.kubernetes.io/name: *name
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: *name
        app.kubernetes.io/name: *name
    spec:
      restartPolicy: Never
      containers:
        - name: add-schema-grants
          image: mariadb:11
          env:
            - name: DB_NAMES
              value: "${DB_NAMES:-${APP}}"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "${NAMESPACE}-mariadbuser-root"
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: "${NAMESPACE}-mariadbuser-root"
                  key: port
            - name: MARIADB_PWD
              valueFrom:
                secretKeyRef:
                  name: "${NAMESPACE}-mariadbuser-root"
                  key: password
            - name: DB_USER
              value: "${DB_USER:-${APP}}"
          command:
            - /bin/bash
            - -c
          args:
            - |
              for DB in $DB_NAMES; do
                mariadb \
                  -h "$DB_HOST" \
                  -P "${DB_PORT:-3306}" \
                  -u root \
                  -p"$MARIADB_PWD" \
                  -e "CREATE DATABASE IF NOT EXISTS \`$DB\`;
                      GRANT ALL PRIVILEGES ON \`$DB\`.* TO '$DB_USER'@'%';
                      FLUSH PRIVILEGES;"
              done
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 52Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
