---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bws-cache
  target:
    name: *name
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: *name
            items:
              - key: client-info.yml
  dataFrom:
  - extract:
      key: synology-csi
