---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bws-cache
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        host: "{{ .host }}"
        port: "{{ .port }}"
        https: "{{ .https }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
        mountOptions: "dir_mode=0775,file_mode=0664,uid=0,gid=0,noperm,mfsymlinks,noserverino,multichannel,max_channels=4"
  dataFrom:
  - extract:
      key: synology-csi
