---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
 - ./externalsecret.yaml
 - ./helmrelease.yaml
configMapGenerator:
  - name: client-info-secret
    files:
      - client-info.yml=./resources/client-info.yml
generatorOptions:
  disableNameSuffixHash: true
