apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-secret
    namespace: storage
stringData:
    client-info.yml: ENC[AES256_GCM,data:OP2/7JJKqwQjeujvBhkke8PfTlan4kiflLHdG6n/60k/20r91aG1temiXjGEgQuyd0cxq6iuLmejqR/n3x6dGbaUw9FWzB7QWhsNGTwmhrWoUv2qITOe7OgyJFTFgnvIycGj7Psq2+xpQWOYYY7bBlCDpBpHkm84nXUdOjTQS5CxyH9efTrvUW0DViShgo7ar7dUR5Y3UDLmoOGLgHZK4gEiKXzUZGCB5GJAnKjSnoJxbh5Hl0zhp5yvHblV9LMOyW3a+EMbZwcyL9rvQe59HxzXCNGBIF+m7SC3dfvlLWQarW3PWQq15QHyHVh83MzpJ9flhHlkfCyiygxDSy1u1cGRLwSktv8gGy7UJqS4oIqpn3myOc8tLVDJnq0fQHl6LAofYMY8NJkqIEVzuEQK/PnJkTcTrSVoqBQLNI6Zd+MVXEZdtM/OeBGjufkwKFtHFjI2oAl9zwoYKi4UFFA59vf2kBRHmCiqJzDOgRNgBCBpLKgoQ0zStrdTWoS8KniOJiOKxKnNHNk9wjtjR7XxZ7AhAKvK1Mf/AtTPn2QH0vlSvgNYs7jGqD4EM3qE0gVrQ3ekdxtYOichIPC4qN+mf1IyFvI/NUlfw/BiyZOVUe7y+wNruov67Y7/yJlxk2hMfxpsaIZOJNjJPfV84v/fuZxNjrEQImWqNwzlRS1AMD8SghFgseO8ovvf4TJKtOKXlwoXvNN7oQnZ1BJ+7beJkmTv+/70s2RBwDVrAq+/rAQ4NOx/yQYPaopBz+Q=,iv:z1BQ2tgR0zdPE8dNTbKAx5ie4ADnKpXKFHOhVuoIzrg=,tag:8BqCxIdz+UJE8QmxMDuE/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbTRYZUZSd1VBUkVCaGlK
            UE55VGRGY05rZUN5Y05pMC9DSjRCWkRoY0drCnZJZGJ5a3ZBT25rcE94RitURm94
            MjdwSEFYWkhpM1RDNkpiYlhISlQ2ZzAKLS0tIDZ6SnpHSFJpaUJ6VENpSDV6bmpn
            am9zZGptVkJaaFVTTEVXNndnTWhRUVUKovi9dBtryMn3cOApCoJMqPeKyefRR9tp
            1d2tX2hxlO3Yv03bD7rGHhGgu+q1D6VFXF+16abl81+FRVhQObCG7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T01:57:32Z"
    mac: ENC[AES256_GCM,data:39pZcF7ZuJW7zQyubTCH6M8MDZvKrTGapcRaUxfAzNTrxa6Yk2jFGk3Z8uMuUuwq/sGmuTvW77X1NBVpTgFXMWCJsVNpaxeu1QlcRVWZ7dVwOKWHoQnmrwfToUtXvNK2hj/YcMN6dC7DdptPZTcHxRVlYMBKellXHuGWq4N7JKc=,iv:fiHoKzPiQt4EmDxnklTcl65tGl2KFLRk/nwJcE8W25I=,tag:hwMWnECzDjb4W5gcOlx5jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
