---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: syno-storage
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  dsm: '10.100.150.10'
  location: '/volume1'
  formatOptions: '--nodiscard'
reclaimPolicy: Retain
allowVolumeExpansion: true
