---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dracomir
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      dracomir:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/felddy/foundryvtt
              tag: 13.351.0
            env:
              FOUNDRY_HOSTNAME: &host "dracomir.${SECRET_DOMAIN}"
              FOUNDRY_LOCAL_HOSTNAME: *host
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: "true"
              FOUNDRY_TELEMETRY: false
              FOUNDRY_MINIFY_STATIC_FILES: "true"
              FOUNDRY_PROTOCOL: "4"
              FOUNDRY_PROXY_PORT: "443"
              FOUNDRY_PROXY_SSL: "true"
              NPM_CONFIG_CACHE: /data/npm-cache
              NPM_CONFIG_PREFIX: /data/npm-global
              CONTAINER_PATCH_URLS: https://gist.githubusercontent.com/felddy/a02d66c3817f8223652d96febe580153/raw/foundryvtt-module-check.sh
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 200m
                memory: 4Gi

          filebrowser:
            image:
              repository: ghcr.io/gtsteffaniak/filebrowser
              tag: 1.2.2-stable@sha256:0e8f0841fe731ef82db285af510e61fed7ad0a7622bf8d39ca6f3492930f8b58
            env:
              TZ: ${TIMEZONE}
              FILEBROWSER_CONFIG: "/config/config.yaml"
            envFrom:
              - secretRef:
                  name: *app
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 25m
                memory: 64Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        # annotations:
        #   gatus.home-operations.com/endpoint: |
        #     group: external
        #     alerts:
        #       - type: pushover
        ports:
          http:
            port: &port 30000

      filebrowser:
        controller: dracomir
        ports:
          http:
            port: &fbPort 80

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: foundryvtt
          gethomepage.dev/name: dracomir
          gethomepage.dev/icon: *app
          gethomepage.dev/description: dracomir FoundryVTT
          gethomepage.dev/widget.type: *app
          gethomepage.dev/widget.url: "http://dracomir.{{ .Release.Namespace }}"
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

      filebrowser:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: foundryvtt
          gethomepage.dev/name: dracomir-files
          gethomepage.dev/icon: filebrowser
          gethomepage.dev/description: dracomir File Browser
        hostnames: ["dracomir-files.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: filebrowser
                port: *fbPort
    configMaps:
      config:
        data:
          config.yaml: |-
            auth:
              methods:
                oidc:
                  enabled: true
                  issuerUrl: https://auth.${SECRET_DOMAIN}
                  scopes: email openid profile groups
                  userIdentifier: preferred_username
                  createUser: true
            server:
              database: /home/filebrowser/data/filebrowser.db
              cacheDir: /home/filebrowser/tmp/.cache
              sources:
                - path: /data
                  config:
                    defaultEnabled: true
    persistence:
      data:
        globalMounts:
          - path: /data
        path: /volume1/dracomir
        server: ${SYNOLOGY_HOSTNAME}
        type: nfs

      config:
        type: configMap
        identifier: config

