apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oUz9yMi95FGESCvX4/xplcbxrmOWLcym725UWgYnW+GHjvpz9HRRFA==,iv:ZVU2ppZ2KlWv32cAONaphRi1K8Lf31ngFVKatoc8jmE=,tag:6h5wP+RVgysWEmv0cBkJoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdDhzZzhaRVRGSHNONkIr
            N1lMdnpjWTlkV0oyU1lwb0hLaTEyb2xlMFNVCnh2OGxVci9jWURabnQzT0kzTWli
            czRjZG5UdW9lT3RjTmRoZWJpMWdrUFEKLS0tIDlwbU9nWU9ZUkNnSnkxZ3kzZGhL
            ZERqU0FDNmp1VmRTZ0xZWkI1ZnJseTQKlddf6/pBxTGY+41q+Z7LLih15gunSA4L
            ZgUXHg/yur4xwLqlBkNKoN837XCKgx4deoZWkSp393sXkQJ4WiZMsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T19:41:17Z"
    mac: ENC[AES256_GCM,data:BNOqYu4QySfAWv6MWQVRr2U+0e5pcaNNXkEd6ViWlyMlV6kFkwXWym+ifVUqWL/ZKtCXCtxeuL22s6DMa8FqX/X2dAsJRx/Wh6ovNPMAu1zYlrw+7WxuOomYWdPMCMUxJDPpbJoBslhnq42MgBu7+JgjIFKn/nIdt6SStibw+0o=,iv:xRc3BWiRVdGRwLvFsfkz6R6xqcLr2P6aJ2CkpDa3HQg=,tag:ZafPmbmKLw6LVRuZBL6HhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
