apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9U5VSYBnPAotm6SF8wiHbzCqNQIrNwq5mmqVXCBL6mbWwHtRaNl3Dw==,iv:DWWlttLSjh0z8FMFhzZBdaIq3LVgQxFRQWW77xI74pY=,tag:c3lVqhC0OQ6KWMy5++/Kvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNzdqc1NPdVV6VndVRjk3
            VDdmdDF1cWltNkNLZ1NBZmZXbmdvWXZxejNRCnNFVHJVOG93Yiswei81MUhaY3Ew
            UncrcmE5TitLbkVvSS9hY3BkQlFneVEKLS0tIHZWZENMTUNpRGlWOTQwYVYwWGFT
            WW5SVFl6THdxcmRDcVJXTjRHckpBUW8KXjjq3fI0CMf+jFWwwhDJyxvPg6J5R6B9
            6RnXpw1VLJpGVrKEdxvhz6qusC8OKzR4bnCyDOSF0zzE0vG5LPrxpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T16:44:00Z"
    mac: ENC[AES256_GCM,data:A+XAmw7Vh03p+uYpjiv1mLHFlGvwXKE6AYpQNH65rdUYDlgRgxMiHts6soNdQ/ynxkC3ZkVKOkxxPoxNXgXTRNKHRMVs2d9uf5DgZ7ab/xwZrIcddW/kcA2GsA9tiVDkEMwOOD/gEno9+84ERdm79W10INDSlDEwD9us9B9errU=,iv:UKjLEOD95DOXXhciJyqZoS9gW1qLQe9hN3PcVS2s+xs=,tag:SriQ7E91vNX1UxQKo7t/WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
