apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:tZY6PJH5k/ygv+maKD4uXIpCgHjDrio+FB7JdWrw221PZCxpCCPMpQ==,iv:Ju4ykMOSIueLwoLm6A1dFt8x/Dj39mK2jorgOGE6/B0=,tag:tRyUVlyClDDFtMoBhdZfcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg4jrx806h0a40ma7pzcxlf4773l2jdk5t48d93kvuhxzg5wg9jsvkznsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRGhBYUVPV3h3VE5jSm1H
            MDA0bzJBcFkrTnVHdVMwNmwrMXFJbFArTWc0ClM5dFNROXFFc1lBdDU1UGQyWS9T
            R25YV0VsUWpYOEp4UjJKRXBIYTRDb3cKLS0tIDR4c0YyR3puakhTUUdSWW5WS0hK
            MTZaMHlrTXFSa0Rpbk1xSzZIdnZscWMKgos13K0uBq+re/mZJl5EgwWT8aHEbnpG
            QPzfWWz+BYZgBG6xy09NmKSQX+RurfW/cjZdLjwgbwWoxfdApLhdng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T01:09:56Z"
    mac: ENC[AES256_GCM,data:O1/Wpd3uJrtW2Kab9QE3VKCEkj1lUqvqkEr6nMBclCm5czmG4wWzzUnZD9yJI+cshd75Td19NgmfkkErBV5qketURgyeNIze8B/J4/fRLFOVavLlyc6o3HHUzHs+nEF4ZxL1e6Smhcz/gRayCGU9iafd1fdMUtP0cOmxzIjxxOY=,iv:DIqYxshB6/XqZTlsYOWh4sSpFLeBRSUy+rqnkN/OjtM=,tag:LNPAi83wav//kuQcopTdIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
