apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: seerr
  namespace: media
spec:
  copyMethod: Snapshot

  repository:
    kind: ClusterRepository
    name: nas

  retention:
    keepDaily: 10
    keepHourly: 24
    keepMonthly: 3
    keepWeekly: 5

  sources:
    - pvc:
        name: seerr
      sourcePathStrategy: PvcName

  volumeSnapshotClassName: csi-ceph-blockpool

---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: seerr
  namespace: media
spec:
  policyRef:
    name: seerr
  schedule:
    cron: "0 * * * *"
